// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../application/models.js";

export class CapabilityOption {
    /**
     * Creates a new CapabilityOption instance.
     * @param {Partial<CapabilityOption>} [$$source = {}] - The source object to create the CapabilityOption.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["values"] = undefined;
        }
        if (!("numeric" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["numeric"] = false;
        }
        if (!("synthetic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["synthetic"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["min"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["max"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["increment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["precision"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CapabilityOption}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField4_0($$parsedSource["values"]);
        }
        return new CapabilityOption(/** @type {Partial<CapabilityOption>} */($$parsedSource));
    }
}

export class CapabilityView {
    /**
     * Creates a new CapabilityView instance.
     * @param {Partial<CapabilityView>} [$$source = {}] - The source object to create the CapabilityView.
     */
    constructor($$source = {}) {
        if (!("capturedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["capturedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pressModel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serialNumber"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("optionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["optionCount"] = 0;
        }
        if (!("excludedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["excludedCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ServerPresetView[] | undefined}
             */
            this["presets"] = undefined;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {CapabilityOption[]}
             */
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CapabilityView}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField7_0($$parsedSource["presets"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new CapabilityView(/** @type {Partial<CapabilityView>} */($$parsedSource));
    }
}

export class ConnectionDraft {
    /**
     * Creates a new ConnectionDraft instance.
     * @param {Partial<ConnectionDraft>} [$$source = {}] - The source object to create the ConnectionDraft.
     */
    constructor($$source = {}) {
        if (!("ipAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipAddress"] = "";
        }
        if (!("secretKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secretKey"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionDraft instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionDraft}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionDraft(/** @type {Partial<ConnectionDraft>} */($$parsedSource));
    }
}

export class ConnectionResult {
    /**
     * Creates a new ConnectionResult instance.
     * @param {Partial<ConnectionResult>} [$$source = {}] - The source object to create the ConnectionResult.
     */
    constructor($$source = {}) {
        if (!("connection" in $$source)) {
            /**
             * @member
             * @type {application$0.ConnectionSnapshot}
             */
            this["connection"] = (new application$0.ConnectionSnapshot());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField0_0($$parsedSource["connection"]);
        }
        return new ConnectionResult(/** @type {Partial<ConnectionResult>} */($$parsedSource));
    }
}

export class Overview {
    /**
     * Creates a new Overview instance.
     * @param {Partial<Overview>} [$$source = {}] - The source object to create the Overview.
     */
    constructor($$source = {}) {
        if (!("serverAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverAddress"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pressModel"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("latencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (!("optionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["optionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Overview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Overview(/** @type {Partial<Overview>} */($$parsedSource));
    }
}

export class PreviewState {
    /**
     * Creates a new PreviewState instance.
     * @param {Partial<PreviewState>} [$$source = {}] - The source object to create the PreviewState.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("connection" in $$source)) {
            /**
             * @member
             * @type {application$0.ConnectionSnapshot}
             */
            this["connection"] = (new application$0.ConnectionSnapshot());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CapabilityView | null | undefined}
             */
            this["capabilities"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField1_0($$parsedSource["connection"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField2_0($$parsedSource["capabilities"]);
        }
        return new PreviewState(/** @type {Partial<PreviewState>} */($$parsedSource));
    }
}

export class ServerPresetView {
    /**
     * Creates a new ServerPresetView instance.
     * @param {Partial<ServerPresetView>} [$$source = {}] - The source object to create the ServerPresetView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPresetView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPresetView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerPresetView(/** @type {Partial<ServerPresetView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ServerPresetView.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CapabilityOption.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = application$0.ConnectionSnapshot.createFrom;
const $$createType6 = CapabilityView.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
