// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ConnectionDraft} input
 * @returns {$CancellablePromise<$models.ConnectionResult>}
 */
export function ApplyConnection(input) {
    return $Call.ByName("api-automation/internal/appwails.Service.ApplyConnection", input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionResult>}
 */
export function CancelConnectionChange() {
    return $Call.ByName("api-automation/internal/appwails.Service.CancelConnectionChange").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CapabilityView>}
 */
export function DiscoverCapabilities() {
    return $Call.ByName("api-automation/internal/appwails.Service.DiscoverCapabilities").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Overview>}
 */
export function RefreshOverview() {
    return $Call.ByName("api-automation/internal/appwails.Service.RefreshOverview").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionResult>}
 */
export function StartConnectionChange() {
    return $Call.ByName("api-automation/internal/appwails.Service.StartConnectionChange").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PreviewState>}
 */
export function State() {
    return $Call.ByName("api-automation/internal/appwails.Service.State").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.ConnectionDraft} input
 * @returns {$CancellablePromise<$models.ConnectionResult>}
 */
export function TestConnection(input) {
    return $Call.ByName("api-automation/internal/appwails.Service.TestConnection", input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ConnectionResult.createFrom;
const $$createType1 = $models.CapabilityView.createFrom;
const $$createType2 = $models.Overview.createFrom;
const $$createType3 = $models.PreviewState.createFrom;
