package reportxlsx

import (
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/xuri/excelize/v2"
)

const (
	excelMaxRows       = 1_048_576
	excelMaxColumns    = 16_384
	resultHeaderRows   = 2
	fixedResultColumns = 8
)

type Report struct {
	Summary         Summary
	ResultsPath     string
	AttributeLabels map[string]string
}

type Stats struct {
	Total           int
	Passed          int
	Failed          int
	Errors          int
	TotalDurationMS int64
}

type attributeColumn struct {
	ID    string
	Label string
}

func Export(path string, report Report) (Stats, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return Stats{}, errors.New("excel export path is required")
	}
	if !strings.EqualFold(filepath.Ext(path), ".xlsx") {
		path += ".xlsx"
	}
	if strings.TrimSpace(report.ResultsPath) == "" {
		return Stats{}, errors.New("stored automation results are unavailable")
	}

	stats, attributes, err := inspectResults(report.ResultsPath, report.AttributeLabels)
	if err != nil {
		return Stats{}, err
	}
	if stats.Total > excelMaxRows-resultHeaderRows {
		return Stats{}, fmt.Errorf("result count %d exceeds Excel's maximum of %d data rows", stats.Total, excelMaxRows-resultHeaderRows)
	}
	if fixedResultColumns+2*len(attributes) > excelMaxColumns {
		return Stats{}, fmt.Errorf("attribute count %d exceeds Excel's column limit", len(attributes))
	}

	workbook := excelize.NewFile()
	defer workbook.Close()
	if err := workbook.SetSheetName("Sheet1", "Summary"); err != nil {
		return Stats{}, fmt.Errorf("name summary sheet: %w", err)
	}
	if _, err := workbook.NewSheet("Results"); err != nil {
		return Stats{}, fmt.Errorf("create results sheet: %w", err)
	}

	styles, err := createStyles(workbook)
	if err != nil {
		return Stats{}, err
	}
	if err := writeSummarySheet(workbook, report.Summary, stats, styles); err != nil {
		return Stats{}, err
	}
	if err := writeResultsSheet(workbook, report.ResultsPath, attributes, styles); err != nil {
		return Stats{}, err
	}
	workbook.SetActiveSheet(0)
	if err := workbook.SetDocProps(&excelize.DocProperties{
		Creator:     "API Automation",
		Title:       "Fiery API Automation Test Results",
		Subject:     "Automation run summary and set/get verification results",
		Description: "Generated by API Automation. Credentials are intentionally excluded.",
		Created:     time.Now().UTC().Format(time.RFC3339),
	}); err != nil {
		return Stats{}, fmt.Errorf("set workbook properties: %w", err)
	}
	if err := saveWorkbookAtomically(workbook, path); err != nil {
		return Stats{}, err
	}
	return stats, nil
}

func inspectResults(path string, labels map[string]string) (Stats, []attributeColumn, error) {
	stats := Stats{}
	attributeIDs := map[string]struct{}{}
	err := forEachResult(path, func(result Result) error {
		stats.Total++
		switch strings.ToUpper(strings.TrimSpace(result.Result)) {
		case "PASS":
			stats.Passed++
		case "FAIL":
			stats.Failed++
		default:
			stats.Errors++
		}
		if result.DurationMS > 0 && stats.TotalDurationMS <= math.MaxInt64-result.DurationMS {
			stats.TotalDurationMS += result.DurationMS
		}
		for id := range result.SetValues {
			attributeIDs[id] = struct{}{}
		}
		for id := range result.GetValues {
			attributeIDs[id] = struct{}{}
		}
		return nil
	})
	if err != nil {
		return Stats{}, nil, err
	}

	labelCounts := map[string]int{}
	columns := make([]attributeColumn, 0, len(attributeIDs))
	for id := range attributeIDs {
		label := strings.TrimSpace(labels[id])
		if label == "" {
			label = id
		}
		labelCounts[label]++
		columns = append(columns, attributeColumn{ID: id, Label: label})
	}
	for index := range columns {
		if labelCounts[columns[index].Label] > 1 {
			columns[index].Label += " (" + columns[index].ID + ")"
		}
	}
	sort.Slice(columns, func(i, j int) bool {
		if columns[i].Label != columns[j].Label {
			return columns[i].Label < columns[j].Label
		}
		return columns[i].ID < columns[j].ID
	})
	return stats, columns, nil
}

type workbookStyles struct {
	title, label, value     int
	header, subheader       int
	pass, fail, exportError int
	mismatch                int
}

func createStyles(workbook *excelize.File) (workbookStyles, error) {
	newStyle := func(style *excelize.Style) (int, error) {
		id, err := workbook.NewStyle(style)
		if err != nil {
			return 0, fmt.Errorf("create workbook style: %w", err)
		}
		return id, nil
	}
	styles := workbookStyles{}
	var err error
	if styles.title, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Size: 18, Color: "FFFFFF"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"1F4E78"}, Pattern: 1}, Alignment: &excelize.Alignment{Vertical: "center"}}); err != nil {
		return styles, err
	}
	if styles.label, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "1F1F1F"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"D9EAF7"}, Pattern: 1}, Alignment: &excelize.Alignment{Vertical: "top", WrapText: true}}); err != nil {
		return styles, err
	}
	if styles.value, err = newStyle(&excelize.Style{Alignment: &excelize.Alignment{Vertical: "top", WrapText: true}}); err != nil {
		return styles, err
	}
	headerBorder := []excelize.Border{{Type: "left", Color: "FFFFFF", Style: 1}, {Type: "right", Color: "FFFFFF", Style: 1}, {Type: "top", Color: "FFFFFF", Style: 1}, {Type: "bottom", Color: "FFFFFF", Style: 1}}
	if styles.header, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "FFFFFF"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"1F4E78"}, Pattern: 1}, Border: headerBorder, Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center", WrapText: true}}); err != nil {
		return styles, err
	}
	if styles.subheader, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "FFFFFF"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"4472C4"}, Pattern: 1}, Border: headerBorder, Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center", WrapText: true}}); err != nil {
		return styles, err
	}
	if styles.pass, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "006100"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"C6EFCE"}, Pattern: 1}, Alignment: &excelize.Alignment{Horizontal: "center"}}); err != nil {
		return styles, err
	}
	if styles.fail, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "9C0006"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"FFC7CE"}, Pattern: 1}, Alignment: &excelize.Alignment{Horizontal: "center"}}); err != nil {
		return styles, err
	}
	if styles.exportError, err = newStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Color: "9C5700"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"FFEB9C"}, Pattern: 1}, Alignment: &excelize.Alignment{Horizontal: "center"}}); err != nil {
		return styles, err
	}
	if styles.mismatch, err = newStyle(&excelize.Style{Font: &excelize.Font{Color: "9C0006"}, Fill: excelize.Fill{Type: "pattern", Color: []string{"FFC7CE"}, Pattern: 1}}); err != nil {
		return styles, err
	}
	return styles, nil
}

func writeSummarySheet(workbook *excelize.File, summary Summary, stats Stats, styles workbookStyles) error {
	const sheet = "Summary"
	if err := workbook.MergeCell(sheet, "A1", "D1"); err != nil {
		return fmt.Errorf("merge summary title: %w", err)
	}
	if err := workbook.SetCellValue(sheet, "A1", "Fiery API Automation Test Report"); err != nil {
		return err
	}
	if err := workbook.SetCellStyle(sheet, "A1", "D1", styles.title); err != nil {
		return err
	}
	if err := workbook.SetRowHeight(sheet, 1, 32); err != nil {
		return err
	}
	if err := workbook.SetColWidth(sheet, "A", "A", 28); err != nil {
		return err
	}
	if err := workbook.SetColWidth(sheet, "B", "B", 48); err != nil {
		return err
	}
	if err := workbook.SetColWidth(sheet, "C", "D", 18); err != nil {
		return err
	}

	rows := []struct {
		label string
		value any
	}{
		{"Generated at", time.Now().Format("2006-01-02 15:04:05 MST")},
		{"Run status", fallback(summary.Status, "Unknown")},
		{"Server IP / URL", fallback(summary.ServerIP, "Unknown")},
		{"Server name", fallback(summary.ServerName, "Unknown")},
		{"Serial number", fallback(summary.SerialNumber, "Unknown")},
		{"Server version", fallback(summary.ServerVersion, "Unknown")},
		{"Session login API", fallback(summary.SessionLoginPath, "Unknown")},
		{"Queues discovered", summary.QueuesDiscovered},
		{"Options discovered", summary.OptionsDiscovered},
		{"Run started", formatTime(summary.StartedAt)},
		{"Run completed", formatTime(summary.CompletedAt)},
		{"Elapsed wall-clock time", elapsedDuration(summary.StartedAt, summary.CompletedAt)},
		{"Combined test duration", formatDuration(time.Duration(stats.TotalDurationMS) * time.Millisecond)},
		{"Test files selected", summary.TestFileCount},
		{"Generated combinations", summary.CombinationCount},
		{"Fiery server preset", fallback(summary.ServerPreset, "None")},
		{"Run modes", strings.Join(summary.RunModes, ", ")},
		{"Combination strategy", fallback(summary.Strategy, "Unknown")},
		{"Parallel workers", summary.Workers},
		{"Planned tests", summary.PlannedTests},
		{"Executed tests", stats.Total},
		{"Passed", stats.Passed},
		{"Failed", stats.Failed},
		{"Errors", stats.Errors},
		{"Pass rate", passRate(stats)},
		{"Constraint-conflicting combinations skipped", summary.ConstraintSkipped},
		{"Verification note", "PASS requires the selected lifecycle outcome as well as strict attribute verification when attributes are selected. Process and Hold/RIP also require successful status/state and raster/page evidence. Fiery may omit attributes that equal the discovered server default; the application accounts for that."},
		{"Security note", "Passwords, API keys, and session cookies are not exported."},
	}
	for index, row := range rows {
		excelRow := index + 3
		labelCell := fmt.Sprintf("A%d", excelRow)
		valueCell := fmt.Sprintf("B%d", excelRow)
		if err := workbook.SetCellValue(sheet, labelCell, row.label); err != nil {
			return err
		}
		if err := workbook.SetCellValue(sheet, valueCell, row.value); err != nil {
			return err
		}
		if err := workbook.SetCellStyle(sheet, labelCell, labelCell, styles.label); err != nil {
			return err
		}
		if err := workbook.SetCellStyle(sheet, valueCell, valueCell, styles.value); err != nil {
			return err
		}
	}
	if err := workbook.SetPanes(sheet, &excelize.Panes{Freeze: true, YSplit: 2, TopLeftCell: "A3", ActivePane: "bottomLeft"}); err != nil {
		return fmt.Errorf("freeze summary header: %w", err)
	}
	return nil
}

func writeResultsSheet(workbook *excelize.File, resultsPath string, attributes []attributeColumn, styles workbookStyles) error {
	const sheet = "Results"
	stream, err := workbook.NewStreamWriter(sheet)
	if err != nil {
		return fmt.Errorf("create results stream: %w", err)
	}
	if err := stream.SetColWidth(1, 1, 26); err != nil {
		return err
	}
	if err := stream.SetColWidth(2, 2, 36); err != nil {
		return err
	}
	if err := stream.SetColWidth(3, 3, 14); err != nil {
		return err
	}
	if err := stream.SetColWidth(4, 4, 24); err != nil {
		return err
	}
	if err := stream.SetColWidth(5, 6, 20); err != nil {
		return err
	}
	if err := stream.SetColWidth(7, 7, 30); err != nil {
		return err
	}
	if err := stream.SetColWidth(8, 8, 52); err != nil {
		return err
	}
	if len(attributes) > 0 {
		if err := stream.SetColWidth(fixedResultColumns+1, fixedResultColumns+2*len(attributes), 24); err != nil {
			return err
		}
	}
	if err := stream.SetPanes(&excelize.Panes{Freeze: true, XSplit: fixedResultColumns, YSplit: 2, TopLeftCell: "I3", ActivePane: "bottomRight"}); err != nil {
		return err
	}
	for column := 1; column <= fixedResultColumns; column++ {
		name, _ := excelize.ColumnNumberToName(column)
		if err := stream.MergeCell(name+"1", name+"2"); err != nil {
			return err
		}
	}
	for index := range attributes {
		startColumn := fixedResultColumns + 1 + index*2
		startName, _ := excelize.ColumnNumberToName(startColumn)
		endName, _ := excelize.ColumnNumberToName(startColumn + 1)
		if err := stream.MergeCell(startName+"1", endName+"1"); err != nil {
			return err
		}
	}

	header := make([]interface{}, fixedResultColumns+2*len(attributes))
	header[0] = excelize.Cell{StyleID: styles.header, Value: "Job ID"}
	header[1] = excelize.Cell{StyleID: styles.header, Value: "Job Name"}
	header[2] = excelize.Cell{StyleID: styles.header, Value: "Result"}
	header[3] = excelize.Cell{StyleID: styles.header, Value: "Mode"}
	header[4] = excelize.Cell{StyleID: styles.header, Value: "Job Status"}
	header[5] = excelize.Cell{StyleID: styles.header, Value: "Job State"}
	header[6] = excelize.Cell{StyleID: styles.header, Value: "Job Error"}
	header[7] = excelize.Cell{StyleID: styles.header, Value: "Lifecycle Verification"}
	subheader := make([]interface{}, len(header))
	for index, attribute := range attributes {
		column := fixedResultColumns + index*2
		header[column] = excelize.Cell{StyleID: styles.header, Value: attribute.Label}
		header[column+1] = excelize.Cell{StyleID: styles.header, Value: ""}
		subheader[column] = excelize.Cell{StyleID: styles.subheader, Value: "Set Value"}
		subheader[column+1] = excelize.Cell{StyleID: styles.subheader, Value: "Get Value"}
	}
	if err := stream.SetRow("A1", header, excelize.RowOpts{Height: 30}); err != nil {
		return err
	}
	if err := stream.SetRow("A2", subheader, excelize.RowOpts{Height: 24}); err != nil {
		return err
	}

	rowNumber := 3
	if err := forEachResult(resultsPath, func(result Result) error {
		row := make([]interface{}, fixedResultColumns+2*len(attributes))
		row[0] = result.JobID
		row[1] = result.JobName
		status := strings.ToUpper(strings.TrimSpace(result.Result))
		statusStyle := styles.exportError
		if status == "PASS" {
			statusStyle = styles.pass
		} else if status == "FAIL" {
			statusStyle = styles.fail
		} else {
			status = "ERROR"
		}
		row[2] = excelize.Cell{StyleID: statusStyle, Value: status}
		row[3] = result.Mode
		row[4] = result.JobStatus
		row[5] = result.JobState
		row[6] = result.JobError
		row[7] = result.Lifecycle
		for index, attribute := range attributes {
			column := fixedResultColumns + index*2
			setValue := result.SetValues[attribute.ID]
			getValue := result.GetValues[attribute.ID]
			if status == "FAIL" && setValue != getValue {
				row[column] = excelize.Cell{StyleID: styles.mismatch, Value: setValue}
				row[column+1] = excelize.Cell{StyleID: styles.mismatch, Value: getValue}
			} else {
				row[column] = setValue
				row[column+1] = getValue
			}
		}
		cell, _ := excelize.CoordinatesToCellName(1, rowNumber)
		rowNumber++
		return stream.SetRow(cell, row)
	}); err != nil {
		return err
	}
	if err := stream.Flush(); err != nil {
		return fmt.Errorf("flush results sheet: %w", err)
	}
	return nil
}

func saveWorkbookAtomically(workbook *excelize.File, path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create export directory: %w", err)
	}
	temp, err := os.CreateTemp(dir, ".api-automation-results-*.xlsx")
	if err != nil {
		return fmt.Errorf("create temporary workbook: %w", err)
	}
	tempPath := temp.Name()
	if err := temp.Close(); err != nil {
		_ = os.Remove(tempPath)
		return err
	}
	defer os.Remove(tempPath)
	if err := workbook.SaveAs(tempPath); err != nil {
		return fmt.Errorf("save temporary workbook: %w", err)
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("replace existing workbook: %w", err)
	}
	if err := os.Rename(tempPath, path); err != nil {
		return fmt.Errorf("publish workbook: %w", err)
	}
	return nil
}

func formatTime(value time.Time) string {
	if value.IsZero() {
		return "Not available"
	}
	return value.Format("2006-01-02 15:04:05 MST")
}

func elapsedDuration(start, end time.Time) string {
	if start.IsZero() || end.IsZero() || end.Before(start) {
		return "Not available"
	}
	return formatDuration(end.Sub(start))
}

func formatDuration(value time.Duration) string {
	if value < 0 {
		return "Not available"
	}
	return value.Round(time.Millisecond).String()
}

func passRate(stats Stats) string {
	if stats.Total == 0 {
		return "0.00%"
	}
	return fmt.Sprintf("%.2f%%", 100*float64(stats.Passed)/float64(stats.Total))
}

func fallback(value, fallbackValue string) string {
	if strings.TrimSpace(value) == "" {
		return fallbackValue
	}
	return value
}
